### ISSUE TITLE
Text and dimensions entities

### ISSUE THREAD

**Issue by bolbol62** [IshmamAbir/vue-dxf-viewer#2]
Hi Ishmam,
Great strat , but you may have to look at the text and dimensions issues still behind yet. also the layers is consuming most of the screen it can be more suttle in apearance if bneeded will expanad .

attached is a dxf file , you may view it in other online viewers or local it will show the text and dimensions where it does not here
[DEMO-2-V4_HEADERS.dxx.zip](https://github.com/IshmamAbir/vue-dxf-viewer/files/15471619/DEMO-2-V4_HEADERS.dxx.zip)

**Comment by IshmamAbir** [comment]
Thanks for the feedback.
Apply your own desired style(like an expansion panel) for the layers  . 
If using Vuetify, then use `v-expansion-panel` component to hide them inside a panel bar (this is the easiest way). 

```vue
<v-expansion-panels>
  <v-expansion-panel title="Title">
        ****  place layer portion here  ****
  </v-expansion-panel>
</v-expansion-panels>
```
