### ISSUE TITLE
Text , dimensions appearance and fonts 

### ISSUE THREAD

**Issue by bolbol62** [IshmamAbir/vue-dxf-viewer#3]
apology, I missed you yesterday - Thanks for guiding me through the layer panel appearance, but still the text and dimensions not rendered in plans .
![Missing text and dimensions](https://github.com/IshmamAbir/vue-dxf-viewer/assets/170912036/a0367fc1-d84e-4a2e-ad90-9c628254a711)

**Comment by bolbol62** [comment]
Is it possible to to pick up the file from the url instead of uploading  ..ex.
https://ishmamabir.github.io/vue-dxf-viewer/.... ? file or url path

**Comment by IshmamAbir** [comment]
> Is it possible to to pick up the file from the url instead of uploading ..ex. https://ishmamabir.github.io/vue-dxf-viewer/.... ? file or url path

convert url to FIle type and hopefully this will work.

1. convert url to File and assign to `inputFile`  value
2. assign the encoded url into the dxfUrl 
 ```js
this.dxfUrl = "https://api.allorigins.win/raw?url=" + encodeURIComponent( **url here** )
```

** you can do a pr with the working demo
